name: certificates
services:
  mysql:
    container_name: certificates-mysql
    image: 'mysql:latest'
    restart:
      always
    env_file:
      - .env
    ports:
      - '${CONTAINER_MYSQL_PORT}:3306'
  app:
    image: 'eclipse-temurin:21-jdk-alpine'
    ports:
      - '8080:8080'
