spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://${MYSQL_HOST}:${CONTAINER_MYSQL_PORT}/${MYSQL_DATABASE}?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
  liquibase:
    enabled: true
  docker:
    compose:
      file: compose-dev.yaml
